export class PageNames {
  public static readonly GUIDE_PAGE: string = 'guidePage';
  public static readonly PRIVACY_PAGE: string = 'privacyPage';
  public static readonly SPLASH_PAGE: string = 'splashPage';
  public static readonly HOME_PAGE: string = 'HomePage';
  public static readonly SCREEN_RECORD: string = 'ScreenRecordPage';
  public static readonly CALC_PAGE = 'calcPage';
  public static readonly STR_CONVERT = 'stringConvertPage';
  public static readonly LOCAL_WEB_PAGE = 'localWebPage';
}