export class SpKeys {
  public static readonly PRIVACY_AGREE: string = 'privacy_agree';
  public static readonly ENABLE_SCAN_PARSE: string = 'enable_scan_parse';
  public static readonly ENABLE_HDC_VISIBLE: string = 'enable_hdc_visible';
  public static readonly FLOAT_CLOCK_ON: string = 'float_clock_on';
  public static readonly CPU_STRESS_ON: string = 'cpu_stress_on';
  public static readonly WEB_SERVER_ON: string = 'web_server_on';
  public static readonly AUTO_START_ENABLED: string = 'auto_start_enabled';
}