[target.aarch64-unknown-linux-ohos]
linker = "C:/Program Files/Huawei/DevEco Studio/sdk/default/openharmony/native/llvm/bin/clang++.exe"
rustflags = ["-C", "link-arg=--target=aarch64-linux-ohos", "-C", "link-arg=--sysroot=C:/Program Files/Huawei/DevEco Studio/sdk/default/openharmony/native/sysroot", "-C", "link-arg=-fuse-ld=lld", "-C", "link-arg=-Wl,--no-rosegment"]
