// Generated by napi-derive — maps to hdc_napi/src/lib.rs
// Plain TCP hdcd communication only. Wireless pairing is in ArkTS layer.

export interface HdcStatus {
  connected: boolean;
  deviceCount?: number;
  error?: string;
}

export interface HdcOutput {
  exitCode: number;
  stdout: string;
  stderr: string;
}

export const hdcCheckConnection: (host?: string, port?: number) => HdcStatus;
export const hdcExecuteShell: (command: string, host?: string, port?: number) => HdcOutput;
export const hdcPing: (host?: string, port?: number) => boolean;
export const hdcServerVersion: (host?: string, port?: number) => HdcOutput;
